// ////////////////////////////////////////////////////////
//
//
//    GENERATED FILE  -  DO NOT EDIT
//
//    This file is generated by generate-index-files.sh
//    the folder's recursive contents.
//
// ////////////////////////////////////////////////////////

/// <reference path='./AdvisorIdProps.d.ts' />
/// <reference path='./ChildrenProps.d.ts' />
/// <reference path='./ClientCareEnvironmentDefaultForCarePhaseProps.d.ts' />
/// <reference path='./ClientCareEnvironmentsProps.d.ts' />
/// <reference path='./ClientIdProps.d.ts' />

