// ////////////////////////////////////////////////////////
//
//
//    GENERATED FILE  -  DO NOT EDIT
//
//    This file is generated by generate-index-files.sh
//    the folder's recursive contents.
//
// ////////////////////////////////////////////////////////

/// <reference path='./ServiceMethod.d.ts' />
/// <reference path='./ServiceMethodFactory.d.ts' />

